SET(CJSON_FOUND "NO")
FIND_PATH(CJSON_INCLUDE_DIR cJSON.h
	/usr/local/include/cjson
	/usr/include/cjson
)

FIND_LIBRARY(CJSON_LIBRARY
	NAMES libcjson cjson
	PATHS /usr/lib64 /usr/lib /usr/local/lib
)

IF (CJSON_INCLUDE_DIR AND CJSON_LIBRARY)
	SET(CJSON_FOUND "YES")
	SET(CJSON_LIBRARYS ${CJSON_LIBRARY})
	SET(HAVE_CJSON 1)
ENDIF(CJSON_INCLUDE_DIR AND CJSON_LIBRARY)

IF (CJSON_FOUND)
	MESSAGE(STATUS "Find cjson: ${CJSON_INCLUDE_DIR} ${CJSON_LIBRARYS}")
ENDIF(CJSON_FOUND)

MARK_AS_ADVANCED(CJSON_INCLUDE_DIR CJSON_LIBRARYS)
